### ISSUE TITLE
Using `enum` for member `size` from `seq::iseq` raises several warnings when sizes are compared. 

### ISSUE THREAD

**Issue by cpp977** [integricho/seq#1]
Is there a special reason for using `enum {size=sizeof...(Is)}` instead of `constexpr static std::size_t size=sizeof...(Is)`?
For me the library compiles fine by just replacing the type of the size member. I tested with gcc 10.2.0 and Clang 11.0.0.

**Comment by afaikafk** [comment]
Hi!
Thanks for taking interest in the library, frankly I thought no one is using it :)
I've applied some changes, among which size is now retrievable through a `static constexpr` function.
To be honest, I kinda lost the motivation to work much on this, as C++ started becoming more and more constexpr supportive with it's standard library facilities.

**Comment by cpp977** [comment]
I find the library quite useful because I need to deal a lot with integer_sequences including filter, replacements and so on. So thanks for coding that!
The new version works fine for me!
The only thing which raises a warning are the `#pragma warning (...)` statements. I guess these are pragmas for MS Visual Studio because clang and gcc ignore these pragmas.
